// Auto-generated from Board Game mod source
// Card reward deck composition per character

pub const IRONCLAD_COMMONS: &[&str] = &[
    "BGAnger",
    "BGBody Slam",
    "BGCleave",
    "BGClothesline",
    "BGFlex",
    "BGHavoc",
    "BGHeavy Blade",
    "BGIron Wave",
    "BGIronWaveShield",
    "BGIronWaveSpear",
    "BGPommel Strike",
    "BGSeeing Red",
    "BGShrug It Off",
    "BGTrue Grit",
    "BGTwin Strike",
    "BGWarcry",
    "BGWild Strike",
];
pub const IRONCLAD_UNCOMMONS: &[&str] = &[
    "BGBattle Trance",
    "BGBlood for Blood",
    "BGBurning Pact",
    "BGCarnage",
    "BGClash",
    "BGCombust",
    "BGDark Embrace",
    "BGDisarm",
    "BGEntrench",
    "BGEvolve",
    "BGFeel No Pain",
    "BGFire Breathing",
    "BGFlame Barrier",
    "BGGhostly Armor",
    "BGHeadbutt",
    "BGInflame",
    "BGMetallicize",
    "BGPerfected Strike",
    "BGPower Through",
    "BGRage",
    "BGRampage",
    "BGRupture",
    "BGSecond Wind",
    "BGSentinel",
    "BGSever Soul",
    "BGShockwave",
    "BGSpot Weakness",
    "BGWhirlwind",
];
pub const IRONCLAD_RARES: &[&str] = &[
    "BGBarricade",
    "BGBerserk",
    "BGBludgeon",
    "BGCorruption",
    "BGDemon Form",
    "BGDouble Tap",
    "BGExhume",
    "BGFeed",
    "BGFiend Fire",
    "BGImmolate",
    "BGImpervious",
    "BGJuggernaut",
    "BGLimit Break",
    "BGOffering",
    "BGUppercut",
];

pub const SILENT_COMMONS: &[&str] = &[
    "BGAcrobatics",
    "BGBackflip",
    "BGBladeDance",
    "BGCloakAndDagger",
    "BGDaggerSpray",
    "BGDaggerThrow",
    "BGDeadlyPoison",
    "BGDeflect",
    "BGDodgeAndRoll",
    "BGPoisonedStab",
    "BGPrepared",
    "BGSlice",
    "BGSneakyStrike",
];
pub const SILENT_UNCOMMONS: &[&str] = &[
    "BGAccuracy",
    "BGAllOutAttack",
    "BGBackstab",
    "BGBane",
    "BGBlur",
    "BGBouncingFlask",
    "BGCalculatedGamble",
    "BGCatalyst",
    "BGChoke",
    "BGConcentrate",
    "BGCripplingCloud",
    "BGDash",
    "BGDistraction",
    "BGEscapePlan",
    "BGExpertise",
    "BGFinisher",
    "BGFlechettes",
    "BGFootwork",
    "BGInfinite Blades",
    "BGLegSweep",
    "BGMasterfulStab",
    "BGNoxiousFumes",
    "BGOutmaneuver",
    "BGPiercingWail",
    "BGPredator",
    "BGReflex",
    "BGRiddleWithHoles",
    "BGSetup",
    "BGSkewer",
    "BGTactician",
    "BGTerror",
];
pub const SILENT_RARES: &[&str] = &[
    "BGAThousandCuts",
    "BGAdrenaline",
    "BGAfterImage",
    "BGBulletTime",
    "BGBurst",
    "BGCorpseExplosion",
    "BGDieDieDie",
    "BGDoppelganger",
    "BGEnvenom",
    "BGGrandFinale",
    "BGMalaise",
    "BGStormOfSteel",
    "BGToolsOfTheTrade",
    "BGUnload",
    "BGWraithForm",
];

pub const DEFECT_COMMONS: &[&str] = &[
    "BGBallLightning",
    "BGBarrage",
    "BGChaos",
    "BGChargeBattery",
    "BGClaw",
    "BGClaw2",
    "BGColdSnap",
    "BGCompileDriver",
    "BGCoolheaded",
    "BGGoForTheEyes",
    "BGLeap",
    "BGRecursion",
    "BGScrape",
    "BGSkim",
    "BGSteamBarrier",
    "BGSweepingBeam",
];
pub const DEFECT_UNCOMMONS: &[&str] = &[
    "BGBeamCell",
    "BGBlizzard",
    "BGCapacitor",
    "BGConsume",
    "BGDarkness",
    "BGDoomAndGloom",
    "BGDoubleEnergy",
    "BGEquilibrium",
    "BGFTL",
    "BGForceField",
    "BGFusion",
    "BGGlacier",
    "BGHeatsinks",
    "BGHologram",
    "BGLoop",
    "BGMachineLearning",
    "BGMelter",
    "BGOverclock",
    "BGRecycle",
    "BGReinforcedBody",
    "BGReprogram",
    "BGStack",
    "BGStorm",
    "BGStreamline",
    "BGSunder",
    "BGTURBO",
    "BGTempest",
];
pub const DEFECT_RARES: &[&str] = &[
    "BGAllForOne",
    "BGAmplify",
    "BGBuffer",
    "BGCoreSurge",
    "BGDefragment",
    "BGEchoForm",
    "BGElectrodynamics",
    "BGFission",
    "BGHyperbeam",
    "BGMeteorStrike",
    "BGMultiCast",
    "BGRainbow",
    "BGSeek",
    "BGStaticDischarge",
    "BGThunderStrike",
];

pub const WATCHER_COMMONS: &[&str] = &[
    "BGCollect",
    "BGConsecrate",
    "BGCrescendo",
    "BGCutThroughFate",
    "BGEmptyBody",
    "BGEmptyFist",
    "BGFlurryOfBlows",
    "BGFlyingSleeves",
    "BGHalt",
    "BGJustLucky",
    "BGProtect",
    "BGThirdEye",
    "BGTranquility",
];
pub const WATCHER_UNCOMMONS: &[&str] = &[
    "BGBattleHymn",
    "BGCarveReality",
    "BGConclude",
    "BGCrushJoints",
    "BGEmptyMind",
    "BGFearNoEvil",
    "BGForeignInfluence",
    "BGForesight",
    "BGIndignation",
    "BGInnerPeace",
    "BGLikeWater",
    "BGMeditate",
    "BGMentalFortress",
    "BGNirvana",
    "BGPerseverance",
    "BGPray",
    "BGProstrate",
    "BGReachHeaven",
    "BGRushdown",
    "BGSandsOfTime",
    "BGSashWhip",
    "BGSignatureMove",
    "BGSimmeringFury",
    "BGStudy",
    "BGSwivel",
    "BGTalkToTheHand",
    "BGTantrum",
    "BGWallop",
    "BGWeave",
    "BGWindmillStrike",
    "BGWorship",
    "BGWreathOfFlame",
];
pub const WATCHER_RARES: &[&str] = &[
    "BGBlasphemy",
    "BGBrilliance",
    "BGConjureBlade",
    "BGDeusExMachina",
    "BGDevaForm",
    "BGDevotion",
    "BGEstablishment",
    "BGJudgment",
    "BGOmega",
    "BGOmniscience",
    "BGRagnarok",
    "BGScrawl",
    "BGSpiritShield",
    "BGVault",
    "BGWish",
];

pub const COLORLESS_COMMONS: &[&str] = &[
    "BGBurn",
    "BGDazed",
    "BGDistilledChaosChoice",
    "BGSlimed",
    "BGVoidCard",
    "BGXCostChoice",
];
pub const COLORLESS_UNCOMMONS: &[&str] = &[
    "BGBlind",
    "BGDarkShackles",
    "BGDramatic Entrance",
    "BGFinesse",
    "BGFlash of Steel",
    "BGGhostly",
    "BGGood Instincts",
    "BGImpatience",
    "BGMadness",
    "BGMind Blast",
    "BGPanacea",
    "BGPanache",
    "BGPurity",
    "BGSadistic Nature",
    "BGSwift Strike",
    "BGThinking Ahead",
    "BGTrip",
];
pub const COLORLESS_RARES: &[&str] = &[
    "BGApotheosis",
    "BGGoldenTicket",
    "BGHandOfGreed",
    "BGMaster of Strategy",
    "BGMayhem",
    "BGThe Bomb",
];

pub const RELICS: &[&str] = &[
    "BGAkabeko",
    "BGAnchor",
    "BGBagOfPreparation",
    "BGBirdFacedUrn",
    "BGBloodVial",
    "BGBlueCandle",
    "BGCalipers",
    "BGCaptainsWheel",
    "BGCentennialPuzzle",
    "BGCharonsAshes",
    "BGDeadBranch",
    "BGDollysMirror",
    "BGDuVuDoll",
    "BGDuality",
    "BGGamblingChip",
    "BGGoldenEye",
    "BGGoldenIdol",
    "BGGremlinHorn",
    "BGHappyFlower",
    "BGHornCleat",
    "BGIceCream",
    "BGIncenseBurner",
    "BGInkBottle",
    "BGLantern",
    "BGMeatOnTheBone",
    "BGMercuryHourglass",
    "BGMoltenEgg2",
    "BGMummifiedHand",
    "BGMutagenicStrength",
    "BGNecronomicon",
    "BGNilrysCodex",
    "BGNinjaScroll",
    "BGOddlySmoothStone",
    "BGOldCoin",
    "BGOmamori",
    "BGOrichalcum",
    "BGPeacePipe",
    "BGPenNib",
    "BGPocketwatch",
    "BGRedMask",
    "BGRedSkull",
    "BGRegalPillow",
    "BGRunicPyramid",
    "BGSelfFormingClay",
    "BGSsserpentHead",
    "BGStoneCalendar",
    "BGStrikeDummy",
    "BGSundial",
    "BGTheAbacus",
    "BGTheBoot",
    "BGTheCourier",
    "BGToolbox",
    "BGToxicEgg2",
    "BGTungstenRod",
    "BGVajra",
    "BGWarPaint",
    "BGWhetstone",
    "BGWingBoots",
];

pub const BOSS_RELICS: &[&str] = &[
    "BGAstrolabe",
    "BGBlackBlood",
    "BGCallingBell",
    "BGCoffeeDripper",
    "BGCursedKey",
    "BGEctoplasm",
    "BGEmptyCage",
    "BGEnchiridion",
    "BGEternalFeather",
    "BGFrozenCore",
    "BGFusionHammer",
    "BGHolyWater",
    "BGMarkOfPain",
    "BGOrrery",
    "BGPandorasBox",
    "BGRingOfTheSerpent",
    "BGSneckoEye",
    "BGSozu",
    "BGTinyHouse",
    "BGWhiteBeast",
    "BGWristBlade",
];

pub const POTIONS: &[&str] = &[
    "BoardGame:BGBlock Potion",
    "BoardGame:BGEnergy Potion",
    "BoardGame:BGExplosive Potion",
    "BoardGame:BGFire Potion",
    "BoardGame:BGSwift Potion",
    "BoardGame:BGWeak Potion",
    "BoardGame:BGFearPotion",
    "BoardGame:BGSteroidPotion",
    "BoardGame:BGGamblersBrew",
    "BoardGame:BGBloodPotion",
    "BoardGame:BGGhostInAJar",
    "BoardGame:BGDistilledChaos",
    "BoardGame:BGEntropicBrew",
    "BoardGame:BGFairyPotion",
    "BoardGame:BGAttackPotion",
    "BoardGame:BGSkillPotion",
    "BoardGame:BGAncientPotion",
    "BoardGame:BGBlock Potion",
    "BoardGame:BGEnergy Potion",
    "BoardGame:BGExplosive Potion",
    "BoardGame:BGFire Potion",
    "BoardGame:BGSwift Potion",
    "BoardGame:BGWeak Potion",
    "BoardGame:BGFearPotion",
    "BoardGame:BGSteroidPotion",
    "BoardGame:BGLiquidMemories",
    "BoardGame:BGSneckoOil",
    "BoardGame:BGElixirPotion",
    "BoardGame:BGCunningPotion",
];

pub const CURSES: &[&str] = &[
    "BGInjury",
    "BGInjury",
    "BGClumsy",
    "BGClumsy",
    "BGParasite",
    "BGParasite",
    "BGRegret",
    "BGRegret",
    "BGWrithe",
    "BGDoubt",
    "BGPain",
    "BGShame",
    "BGDecay",
];
